# Run unit tests, integration tests, and other CI checks
name: ci

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  commitlint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4

  pytest:
    runs-on: ubuntu-latest
    container: python:3.8

    steps:
      - uses: actions/checkout@v2

      - name: Install Poetry
        run: pip3 install poetry

      - name: Unit Tests
        run: poetry run pytest

  pypi-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    container: python:3.8
    steps:
      - uses: actions/checkout@v2

      - name: Install Poetry
        run: pip3 install poetry

      - name: Poetry Build
        run: |
          poetry check
          poetry build

  release:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    needs:
      - pytest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install semantic-release
        run: npm i semantic-release@v18.0.0 conventional-changelog-conventionalcommits@4.6.1

      - name: Release
        env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
